testing another approach

diff --git a/.github/workflows/auto-approve.yaml b/.github/workflows/auto-approve.yaml
--- a/.github/workflows/auto-approve.yaml
+++ b/.github/workflows/auto-approve.yaml
@@ -6,17 +6,10 @@
 name: dependabot-autoapprove
 
 on:
-  # This workflow trigger may lead to malicious PR authors being able to obtain repository write
-  # permissions or stealing repository secrets. 
-  # Please read https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
-  pull_request_target:
+  workflow_run:
+    workflows: [ "build-test" ]
     types:
-      - synchronize
-      - opened
-      - edited
-      - ready_for_review
-      - reopened
-      - unlocked
+      - completed
 
 jobs:
   auto-approve:
@@ -27,33 +20,29 @@ jobs:
 
     steps:
 
+      - name: build-test success
+        if: ${{ github.event.workflow_run.conclusion == 'success' }}
+        run: echo "::notice ::build-test success"
+
+      - name: build-test failure
+        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+        run: |
+          echo "::notice ::build-test failure"
+          exit 1
+
       - name: dependabot metadata
         id: dependabot-metadata
         uses: dependabot/fetch-metadata@v1.1.1
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: wait for build-test to succeed
-        uses: fountainhead/action-wait-for-check@v1.0.0
-        id: wait-build-test
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          checkName: build-test-success
-          ref: ${{ github.event.pull_request.head.sha }}
-
       - name: auto-approve conditions
         id: auto-approve-conditions
         # only auto-approve if this is a minor or patch version update
         if: |
-          (
-            steps.wait-build-test.outputs.conclusion == 'success'
-            &&
-            (
-              ( steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' )
-              ||
-              ( steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' )
-            )
-          )
+          ( steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' )
+          ||
+          ( steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' )
         run: echo "::notice ::auto-approve conditions satisfied"
 
       - name: auto-approve
